### ISSUE TITLE
请问这个一换一机制是个什么思路呢？

### ISSUE THREAD

**Issue by hangvane** [Dawnnnnnn/bili-Mutual-coin#1]
想实现一下，但是没有思路...如何保证真的投币了之类的...

**Comment by Dawnnnnnn** [comment]
诶。。其实早就写完了，一直没传上来，因为用户量太少了。。
保证真的投币是将当前视频的硬币数据存到数据库中，如果收到了某用户的已投币请求，会再次获取视频的硬币数量，如果增加了就是投了。

**Comment by hangvane** [comment]
但是有些细节怎么处理呢？
假如我是个白嫖用户，一直向服务器发送虚假的已投币请求，就指望某一瞬间有吃瓜群众或者用脚本的其他用户投币了，让我的请求通过，这不就撞上了...
如果为了限制这种行为同时减少服务器的压力，限制服务器在x分钟内只接收一次某用户的请求，或者发现刷请求行为就黑名单的话，又会出现恶意用户伪造其他用户身份发送请求，让真正的用户无法使用这个脚本...

**Comment by Dawnnnnnn** [comment]
服务器可以设置阙值啊，五分钟只响应一次请求，多了就拉黑了，其实想彻底解决这个伪造的问题，那只能让用户向服务器端发送cookie，不过我们一开始就在群里小范围的使用，也不会出现这种用户。。
